app:
  - sampling_config:
      k_traces: 32
      temperature: 1.0
      top_p: 0.95
    samples_per_template: 4
    logging: DEBUG  
    experiment:
      # Needs to be it's own class
      onset_on_next_note: true
      # metric_clip: [2.8935,4.7331,5.6616,3.7884] # 0.95 quantile
      # metric_clip: [1.1138, 3.4593, 4.1095, 2.2253] # 0.8 quantile
      # metric_clip: [0.9025, 3.2272, 3.7998, 1.9640] # .75 quantile
      time_points_generator:
        class_path: CIA.ic.FixedStepTimepoints
        init_args:
          eval_step: 0.25
          step: 0.25
      weight:
        class_path: CIA.ic.MovingAverage
        init_args:
          window_size: 1.0
          decay: 0.0
          channel_weight: [
            1.0,
            0.0,
            0.0,
            1.0,
            # 0.56,
            # 0.0,
          ]
      ic_curve:
        class_path: CIA.ic.LinearInterpolation
        init_args:
          relative_time: true
          timepoints: [
            0,
            0.499,
            .500,
            1.0,
          ]
          ics: [
            [0.0, 0.0, 0.0, 0.],
            [7.5, 0.0, 0.0, 7.5],
            [0.0, 0.0, 0.0, 0.],
            [7.5, 0.0, 0.0, 7.5],
        ]
      dataset:
        class_path: DataPiece
        init_args:
          label: batik
          cache_path: /share/hel/home/mathias/.cache/mutdata/pia/dataset_cache/BatikPlaysMozart
          pieces:
            - path: '/share/hel/home/mathias/datasets/batik_plays_mozart/midi/kv331_1.mid'
              start_node: '0:54.5'
              # NOTE: time deltas
              # n_inpaint: '1:05.5'
              n_inpaint: '0:32.3'
              end_window: '0:00.0'
