app:
# NOTE: following the ic curve.
# - k_traces: 1
#   samples_per_template: 16
#   experiment:
#     time_points_generator:
#       class_path: CIA.ic.FixedStepTimepoints
#       init_args:
#         step: 0.5
#     weight:
#       class_path: CIA.ic.MovingAverage
#       init_args:
#         window_size: 0.5
#         c: 1.0
#     dataset:
#       class_path: DataPiece
#       init_args:
#         label: mozart_normal_sampling
#         pieces:
#           - path: '/share/home/mathias/.cache/mutdata/pia/databases/Piano/transcriptions/midi/Mozart, Wolfgang Amadeus, Allegro in C major, K.9a_5a, CJe3ISkn-RM.mid'
#             start_node: 25
#             n_inpaint: 101
#   logging: DEBUG
- sampling_config:
    k_traces: 128
    temperature: 1.0
  samples_per_template: 4
  experiment:
    time_points_generator:
      class_path: CIA.ic.FixedStepTimepoints
      init_args:
        step: 0.5
        eval_step: 0.05
    match_metric: ic
    # weight:
    #   class_path: CIA.ic.MovingAverage
    #   init_args:
    #     window_size: 0.5
    #     # c: [1.0, 'inf', 'inf', 1.0]
    #     decay: 1.0
    #     channel_weight: [1.0, 0.0, 0.0, 1.0]
    weight:
        class_path: CIA.ic.MovingAverage
        init_args:
          # window_size: 0.5
          # c: 0.0
          window_size: 4.0
          decay: 0.2
          # channel_weight: [
          #   1.0,
          #   1.0,
          #   1.0,
          #   1.0,
          #   1.0
          # ]
          channel_weight: [
            1.07,
            # 0.30,
            # 0.45,
            0.0,
            0.0,
            0.73
          ]
    ic_curve:
        class_path: CIA.ic.LinearInterpolation
        init_args:
          relative_time: true
          timepoints: [
            0,
          # 0.499,
          # 0.5,
          1.0]
          ics: [
            # [0, 0., 0., 0.],
            # [25, 0., 0, 25.],
            # [0, 0., 0., 0.],
            # [18.75, 0, 0, 18.75],
            # [18.75, 0, 0, 18.75],
            # [6.25, 0., 0, 6.25],
            [6.25, 0., 0, 6.25],
            [25, 0., 0, 25.],
            
    ]
    dataset:
      class_path: DataPiece
      init_args:
        label: mozart_normal_sampling
        cache_path: /share/hel/home/mathias/.cache/mutdata/pia/dataset_cache/PianoMidi
        pieces:
          - path: '/share/hel/home/mathias/.cache/mutdata/pia/databases/Piano/transcriptions/midi/Mozart, Wolfgang Amadeus, Allegro in C major, K.9a_5a, CJe3ISkn-RM.mid'
            start_node: 25
            n_inpaint: 101
            # start_node: -31
            # n_inpaint: 37
  logging: DEBUG
# - k_traces: 32
#   samples_per_template: 16
#   experiment:
#     time_points_generator:
#       class_path: CIA.ic.FixedStepTimepoints
#       init_args:
#         step: 0.5
#     weight:
#       class_path: CIA.ic.MovingAverage
#       init_args:
#         window_size: 0.5
#         c: 1.0
#     dataset:
#       class_path: DataPiece
#       init_args:
#         label: mozart_normal_sampling
#         pieces:
#           - path: '/share/home/mathias/.cache/mutdata/pia/databases/Piano/transcriptions/midi/Mozart, Wolfgang Amadeus, Allegro in C major, K.9a_5a, CJe3ISkn-RM.mid'
#             start_node: 25
#             n_inpaint: 101
#   logging: DEBUG
# - k_traces: 64
#   samples_per_template: 16
#   experiment:
#     time_points_generator:
#       class_path: CIA.ic.FixedStepTimepoints
#       init_args:
#         step: 0.5
#     weight:
#       class_path: CIA.ic.MovingAverage
#       init_args:
#         window_size: 0.5
#         c: 1.0
#     dataset:
#       class_path: DataPiece
#       init_args:
#         label: mozart_normal_sampling
#         pieces:
#           - path: '/share/home/mathias/.cache/mutdata/pia/databases/Piano/transcriptions/midi/Mozart, Wolfgang Amadeus, Allegro in C major, K.9a_5a, CJe3ISkn-RM.mid'
#             start_node: 25
#             n_inpaint: 101
#   logging: DEBUG
  
# NOTE: opposite the ic curve (inverted saw).
# - k_traces: 16
#   samples_per_template: 16
#   experiment:
#     time_points_generator:
#       class_path: CIA.ic.FixedStepTimepoints
#       init_args:
#         step: 0.5
#     weight:
#       class_path: CIA.ic.MovingAverage
#       init_args:
#         window_size: 0.5
#         c: 1.0
#     dataset:
#       class_path: DataPiece
#       init_args:
#         label: debug
#         pieces:
#           - path: '/share/home/mathias/.cache/mutdata/pia/databases/Piano/transcriptions/midi/Mozart, Wolfgang Amadeus, Allegro in C major, K.9a_5a, CJe3ISkn-RM.mid'
#             start_node: 25
#             n_inpaint: 101
#     ic_curve:
#       class_path: CIA.ic.LinearInterpolation
#       init_args:
#         relative_time: false
#         timepoints: [0, 15.0]
#         ics: [
#           [5, 5, 5, 5.],
#           [1.75, 1.75, 1.75, 1.75],
#         ]
#   logging: DEBUG
# - k_traces: 16
#   samples_per_template: 16
#   experiment:
#     time_points_generator:
#       class_path: CIA.ic.FixedStepTimepoints
#       init_args:
#         step: 0.5
#     weight:
#       class_path: CIA.ic.MovingAverage
#       init_args:
#         window_size: 0.5
#         c: [1.0, 'inf', 'inf', 1.0]
#     dataset:
#       class_path: DataPiece
#       init_args:
#         label: debug
#         pieces:
#           - path: '/share/home/mathias/.cache/mutdata/pia/databases/Piano/transcriptions/midi/Mozart, Wolfgang Amadeus, Allegro in C major, K.9a_5a, CJe3ISkn-RM.mid'
#             start_node: 25
#             n_inpaint: 101
#     ic_curve:
#       class_path: CIA.ic.LinearInterpolation
#       init_args:
#         relative_time: false
#         timepoints: [0, 15.0]
#         ics: [
#           [7.5, 7.5, 7.5, 7.5],
#           [1.0, 1.0, 1.0, 1.0],
#         ]
#   logging: DEBUG